src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]


class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $DateReservation = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    // ajout de condition pour valider le formulaire (champs qui ne doit pas etre vide et date entre qui ne doit pas etre antérieure à la date du jour)
    #[Assert\NotBlank(
        message: 'Veuillez indiquer une date.',
    )]
    private ?\DateTimeInterface $DateEntree = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    // ajout de condition pour valider le formulaire (champs qui ne doit pas etre vide et date sortie qui ne doit pas etre antérieure à la date entrée)
    #[Assert\NotBlank(
        message: 'Veuillez indiquer une date.',
    )]
    #[Assert\GreaterThan(
    propertyPath: "DateEntree", 
    message : 'La date de sortie doit être postérieure à la date d\'entrée.'
    )]
    private ?\DateTimeInterface $DateSortie = null;


    #[ORM\ManyToOne(inversedBy: 'user')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(targetEntity : "Chambre", inversedBy: 'chambre')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Chambre $chambre = null;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateReservation(): ?\DateTimeInterface
    {
        return $this->DateReservation;
    }

    public function setDateReservation(\DateTimeInterface $DateReservation): static
    {
        $this->DateReservation = $DateReservation;

        return $this;
    }

    public function getDateEntree(): ?\DateTimeInterface
    {
        return $this->DateEntree;
    }

    public function setDateEntree(\DateTimeInterface $DateEntree): self
    {
        $this->DateEntree = $DateEntree;

        return $this;
    }

    public function getDateSortie(): ?\DateTimeInterface
    {
        return $this->DateSortie;
    }

    public function setDateSortie(\DateTimeInterface $DateSortie): static
    {
        $this->DateSortie = $DateSortie;

        return $this;
    }


    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getChambre(): ?Chambre
    {
        return $this->chambre;
    }

    public function setChambre(?Chambre $chambre): static
    {
        $this->chambre = $chambre;

        return $this;
    }


}

src/Controller/FullRoomController.php
<?php

namespace App\Controller;

use App\Repository\ChambreRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class FullRoomController extends AbstractController
{
    #[Route('/chambreOcuppee', name: 'chambreOcuppee')] // Définition de la route
    public function index(ChambreRepository $chambreRepository): Response // Injection du repository ChambreRepository
    {

        // Utilisation du repository pour trouver une chambre en appelant la fonction dans le repository
        $fullRoom = $chambreRepository->findOneByRoom();
        $nbrfullRoom = count($fullRoom);
        // dd($fullRoom);
    
        return $this->render('chambre_occupee/index.html.twig', [
            
            'ChambreFull' => $fullRoom,
            'nbrfullRoom'=>$nbrfullRoom,
            
        ]);
    }
}

templates/full_room/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FullRoomController!{% endblock %}

{% block body %}

<style>

 h1 {
        font-size: 24px;
        color: darkblue;
        font-weight: bold;
        font-family: Arial, sans-serif;
    }


</style>


<p style="font-size: 20px; color: darkblue; font-weight: bold; font-family: Arial, sans-serif;">Nombre de chambres
    occupées : {{ nbrChambre }} </p>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Numéro de la chambre</th>
            <th scope="col">Tarif</th>
            <th scope="col">État</th>
            <th scope="col">User</th>
            <th scope="col">Email</th>
            <th scope="col">Téléphone</th>

            <th scope="col">Dates de réservation</th>
        </tr>
    </thead>


    <tbody>
        <tr>
            {% for chambre in FullRoom %}
            <th scope="row">{{ chambre.id }}</th>
            <td>{{ chambre.tarif }} euros</td>
            <td>{{ chambre.etat ? 'libre' : 'occupée' }}</td>

        <td>
            {% for reservationChambre in chambre.reservationChambres %}
            {{ reservationChambre.reservation.user.nom }} {{ reservationChambre.reservation.user.prenom }}<br>
            {% endfor %}
        </td>

        <td>
            {% for reservationChambre in chambre.reservationChambres %}
            {{ reservationChambre.reservation.user.email }}<br>
            {% endfor %}
        </td>
        
        <td>
            {% for reservationChambre in chambre.reservationChambres %}
            {{ reservationChambre.reservation.user.telephone }}<br>
            {% endfor %}
        </td>


        <td>
            {% for reservationChambre in chambre.reservationChambres %}
            {{ reservationChambre.reservation.dateEntree|date('Y-m-d') }} - {{
            reservationChambre.reservation.dateSortie|date('Y-m-d') }}<br>
            {% endfor %}
        </td>

        </tr>
        {% endfor %}
    </tbody>
    
</table>
{% endblock %}