src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'Cette adresse e-mail existe déjà')]

class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;
    private ?string $plainPassword = null;


    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $adresse = null;

    #[ORM\Column(length: 255)]
    private ?string $telephone = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_de_naissance = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Reservation::class)]
    private Collection $user;

    public function __construct()
    {
        $this->user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): static
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getUser(): Collection
    {
        return $this->user;
    }

    public function addUser(Reservation $user): static
    {
        if (!$this->user->contains($user)) {
            $this->user->add($user);
            $user->setUser($this);
        }

        return $this;
    }

    public function removeUser(Reservation $user): static
    {
        if ($this->user->removeElement($user)) {
            // set the owning side to null (unless already changed)
            if ($user->getUser() === $this) {
                $user->setUser(null);
            }
        }

        return $this;
    }


    public function __toString()
    {

        return $this->email;
    }


    /**
     * Get the value of plainPassword
     */ 
    public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    /**
     * Set the value of plainPassword
     *
     * @return  self
     */ 
    public function setPlainPassword($plainPassword)
    {
        $this->plainPassword = $plainPassword;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\Regex;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder

            ->add('email', EmailType::class, [
                'constraints' => [
                    new Email([
                        'message' => 'L\'adresse e-mail n\'est pas valide', // Message d'erreur en cas d'adresse e-mail invalide
                    ]),
                ],
            ])

            ->add('password', PasswordType::class, [
                'label' => 'Mot de passe',
                'mapped' => false,
                'required' => false, // afin eviter de demander le mot de passe dans le formulaire modifier le profil, bloque la soumission du mot de passe
                'attr' => ['autocomplete' => 'new-password'],// Attribut HTML pour l'autocomplétion du champ de mot de passe
                'constraints' => [
                    new Length([  // Vérifie la longueur du mot de passe
                        'min' => 6,
                        'minMessage' => 'Votre mot de passe doit contenir au moins 6 caractères', //message erreur
                        'max' => 10,
                    ]),
                    new Regex([
                        'pattern' => '/^(?=.*[A-Z])(?=.*\d)/',
                        'message' => 'Votre mot de passe doit contenir au moins une lettre majuscule et au moins un chiffre.',
                    ]),
                ],
            ])

            ->add('adresse')

            ->add('telephone', TextType::class, [
                'constraints' => [
                    new Regex([
                        'pattern' => '/^\d+$/',
                        'message' => 'Le numéro de téléphone doit contenir uniquement des chiffres.',
                    ]),
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/', name: 'app_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager, UserPasswordHasherInterface $passwordHasher): Response
    {
        $user->getUser();

        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            // Récupère le mot de passe(données) depuis le champs du formulaire
            $mdpFormulaire = $form->get('password')->getData();

            // vériffie si la variable contient une valeur 
            if (isset($mdpFormulaire)) {

                // hashashe du mot de passe 
                $mdpHashe = $passwordHasher->hashPassword($user, $mdpFormulaire);

                // modification du mot de passe en format hashé dans l'entité user 
                $user->setPassword($mdpHashe);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'registrationForm' => $form->createView(),
        ]);
    }
}

templates/user/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success" id="btn-enregistrement">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier votre profil{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" href="/assets/css/modifierProfil.css">
{% endblock %}


{% block body %}

<div class="container-principal">

    <div class="container">

        <div class="en-tete">
            <h1 id="titreProfil">Modifier votre profil</h1>
        </div>


        {{ form_start(registrationForm) }}


        {{form_label(registrationForm.email) }}
        {{form_widget(registrationForm.email) }}
        {{ form_errors(registrationForm.email) }}


        {{form_label(registrationForm.password) }}
        {{form_widget(registrationForm.password) }}
        {{ form_errors(registrationForm.password) }}


        {{form_label(registrationForm.adresse) }}
        {{form_widget(registrationForm.adresse, {'attr': {'placeholder': 'Votre contenu ici'}}) }}
        {{ form_errors(registrationForm.adresse) }}
        <ul id="liste_adresse"></ul>


        {{form_label(registrationForm.telephone) }}
        {{form_widget(registrationForm.telephone, {'attr': {'placeholder': 'Votre contenu ici'}}) }}
        {{ form_errors(registrationForm.telephone) }}

        <button class="btn btn-success" id="btn-enregistrement">{{ button_label|default('Enregistrer les modifications') }}</button>

        {{ form_end(registrationForm) }}


        <div class="actions">
            <a href="{{ path('app_user_index') }}" class="back-button">Retour</a>
        </div>

    </div>

</div>

<script src="{{asset('assets/js/apiModifierProfil.js')}}"></script>

{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}


{% block stylesheets %}
<link rel="stylesheet" href="/assets/css/profil.css">
{% endblock %}


{% block body %}

<div class="conteneur">

    <div class="bloc-profil">

        {% if app.user %}

        <div class="en-tete">

            <h1 id="titre">{{ app.user.nom }} {{ app.user.prenom }}</h1>

            <div class="photo-profil">
                <img src="/img/venom.jpg" alt="photo_profil" />
            </div>

        </div>


        <div class="user-infos">

            <ul>
                <li>Email:</li>
                <li>{{ app.user.email }}</li>
            </ul>

            <ul>
                <li>Adresse:</li>
                <li>{{ app.user.adresse }}</li>
            </ul>

            <ul>
                <li>Numéro de téléphone</li>
                <li>{{ app.user.telephone}}</li>
            </ul>

            <ul>
                <li>Date de naissance</li>
                <li>{{ app.user.dateDeNaissance|date('d-m-Y')}}</li>
            </ul>

        </div>

        <div class="actions">
            {# <a href="{{ path('app_user_show', {'id': app.user.id}) }}" class="btn btn-black">Show</a> #}
            <a href="{{ path('app_user_edit', {'id': app.user.id}) }}" class="btn btn-custom"><b>Modifier votre profil</b></a>
        </div>

        {% endif %}

    </div>

</div>

{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}User{% endblock %}

{% block stylesheets %}
  <style>

h1 {
    color: #333;
}

table {
    width: 100%;
    border-collapse: collapse;
}

th, td {
    border: 1px solid #ccc;
    padding: 8px;
}

th {
    background-color: #f2f2f2;
    text-align: left;
}

.button-container {
    text-align: center;
}

a.button {
    display: inline-block;
    padding: 8px 16px;
    border-radius: 5px;
    color: #fff;
    text-decoration: none;
    transition: background-color 0.3s;
}

a.button:hover {
    background-color: #333;
}

a.button.button-black {
    background-color: #000;
}

a.button.button-black:hover {
    background-color: #E0B973; 
}

a.button.button-yellow {
    background-color: #E0B973;
}

a.button.button-yellow:hover {
    background-color: black; 
}

    </style>
{% endblock %}


{% block body %}
    <h1>User</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Email</th>
                <td>{{ user.email }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ user.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ user.prenom }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ user.adresse }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ user.telephone }}</td>
            </tr>
        </tbody>
    </table>

   <a class="button button-black" href="{{ path('app_user_index') }}">Back to List</a>
    <a class="button button-yellow" href="{{ path('app_user_edit', {'id': user.id}) }}">Edit</a>
{% endblock %}